/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 moodeng.gltf 
Author: daydev (https://sketchfab.com/daydev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moo-deng-baby-pygmy-hippo-ee0e9e52de954c6cae9160d5f4e49003
Title: Moo Deng: Baby Pygmy Hippo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/moodeng.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} position={[10.649, 148.118, 228.112]} rotation={[-Math.PI / 2, 0, 0]} scale={4.095} />
        <mesh geometry={nodes.Cube001__0.geometry} material={materials.Cube__0} position={[10.649, 104.183, 227.401]} rotation={[-Math.PI / 2, 0, 0]} scale={2.887} />
        <mesh geometry={nodes.Mesh_0_Material_0_0.geometry} material={materials.Material_0} position={[9.798, 152.856, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={317.879} />
      </group>
    </group>
  )
}

useGLTF.preload('/moodeng.gltf')
